"""
Feedback Collection & Iteration Orchestrator - FastAPI Application
Generated by build_system.py on 2025-10-15
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.config import settings
from app.api.v1 import feature_02
from app.api.v1 import feature_03
from app.api.v1 import feature_04
from app.api.v1 import feature_05
from app.api.v1 import feature_06

app = FastAPI(
    title="Feedback Collection & Iteration Orchestrator",
    description="Integrated system combining all features",
    version="1.0.0"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include all feature routers
app.include_router(feature_02.router, prefix="/api/v1", tags=["Real-Time Engagement Tracking"])
app.include_router(feature_03.router, prefix="/api/v1", tags=["Revenue & Conversion Tracking"])
app.include_router(feature_04.router, prefix="/api/v1", tags=["Automated Prioritization Engine"])
app.include_router(feature_05.router, prefix="/api/v1", tags=["Archive & Cleanup Automation"])
app.include_router(feature_06.router, prefix="/api/v1", tags=["Dashboard User Interface"])

@app.get("/")
async def root():
    """Root endpoint."""
    return {
        "system": "Feedback Collection & Iteration Orchestrator",
        "status": "operational",
        "features": 5
    }

@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {"status": "healthy"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
